Pull Request for Code Review
RichardChileya/HelloMicroverse pull request #2
Opened 2022-06-29 15:20 UTC by RichardChileya

2022-06-29 15:46 UTC, Ugboaja-Uchechi requested changes
Hi @RichardChileya , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Great job on setting up your repo 👍 
- README looks professional ✔️ 

## Required Changes ♻️

- **Please make sure you create a `test.md` file and it is being ignored by GitHub.**
- **Please make sure you add all necessary linters specified by Microverse. Kindly follow the [guidelines](https://github.com/microverseinc/linters-config/tree/master/html-css). If you have any problems setting it up you can reach out to me on SLACK @tired coder.**
- **Please make sure you follow GitHub flow rules. You can read through this [article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- **Adding a project description to your pull request.**
- **Adding more commit messages.**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 17:51 UTC, cwaku requested changes
Hi @RichardChileya 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights
- [x] All linters passed 👍🏾 
- [x] Meaningful PR title 💯 
- [x] Good commit messages 👍🏾 

## Required Changes ♻️
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips 🌟  that can improve your code quality 💯 and help you get a better job 💼.

I will guide 📔 you through fixing 🛠️ these bugs, follow my comments down below and make sure you don't miss any of them, in order to get your project approved ✅

- [ ] As required by the previous reviewer, kindly add a `test.md` file the root directory of your repo and use `.gitignore` file to ignore it. A simple way to go about this in your situation is to create a file named `test.md` just like you'd create an `index.html` file. After that add open your `.gitignore` file and type `test.md` inside of it. Commit and then push your changes to github. You'll realise that the `test.md` file isn't pushed together with your files, that's a good thing.

## Optional suggestions
- [ ] Kindly add a description to your PR
- [ ] Good you used Gitflow but on your next projects, kindly have your `feature` branches merge into `main` instead of the opposite. [Read here for more details](https://www.flagship.io/git-branching-strategies/)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 21:11 UTC, BertrandConxy requested changes
Hi @RichardChileya , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights 💪 
- All linters are passing
- Good commit messages

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] It is very important to use the correct GitHub flow. We have to create a pull request from our feature into the main or the master branch which should be always stable and fresh. Unfortunately, you have done the inverse. GitHub flow help us to keep our main branch from bugs because it is our production branch. Please correct the flow, merge the `feature-a` into `main`. 💡 This is very important notice to remember in all your next projects that you will build
- [ ] [OPTIONAL] Also your pull request is not describing what you have done in that branch. You should have called it `Build hello microverse page` or any other alternative. This helps someone who is going to review it to know what to check very easily. 💡 It is important to remember this point in your next projects as it is very important. 
- [ ] [OPTIONAL] Lastly, your pull request body/description area is empty. You have not added any description of what changes you have introduced in this branch. You should have listed what you changed and what you built. For example - Added index.html - Added style.css etc
This gives more detailed information to anyone who is going to review the code about what you have done 😺. It is important also to remember this one in your next projects as it is very important.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 21:11 UTC, BertrandConxy commented on test.md
> +
- [ ] It is really great that you were able to create the `test.md` as suggested by the previous reviewers but you missed the last step which is adding its name in the `.gitignore` file. This is a special file that allows you to hide files or folders from git so that it is not aware of them and can't track them and as a result of this, the files added there can't be pushed and shown on GitHub in your repository. With this requirement, you make sure that you can be able to use it. However, you are so close as I told you 🏃‍♂️. Please add the name `test.md` in your `.gitignore` file and it will be done.
⚠️ Because you have already pushed it on GitHub, you will first need to delete it manually on Github, then locally in your code editor run this command `git rm -r --cached .` this will untrack all your files so that you can be able to hide the other `test.md` file. The next step will be to add its name to the `.gitignore` file. Then run `git add .` to allow git to track all the files again, then run `git commit -m '<message>'` to commit the changes. This will surely work and therefore, the test.md will not be pushed on GitHub

2022-06-30 08:40 UTC, merged

2022-06-30 08:41 UTC, RichardChileya reviewed
Mergiging first branch